[package]
name = "winx"
version = "0.25.1-alpha.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]
description = "Windows API helper library"
documentation = "https://docs.rs/winx"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"

[dependencies]
bitflags = "1.0"
io-lifetimes = "0.1.1"
winapi = { version = "^0.3", features = [
    "std",
    "handleapi",
    "ioapiset",
    "profileapi",
    "winbase",
    "winerror",
    "winioctl",
] }

[badges]
maintenance = { status = "passively-maintained" }

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
